### ISSUE TITLE
Crash when exiting a world

### ISSUE THREAD

**Issue by A00826925** [dantaeusb-mc/Zetter#103]
hi me again, here to report another crash. The game crashes when exiting from a world, here is the error and report:
The game crashed whilst mouseclicked event handler
Error: java.lang.IllegalArgumentException: Attempted to set event phase to NORMAL when already NORMAL

[crashonleave.txt](https://github.com/dantaeusb-mc/Zetter/files/10610075/crashonleave.txt)

This is on the latest update.

**Comment by dantaeusb** [comment]
Accidentally got some changes & fixes skipped on 1.19.2, this bag was already happening in #91, so it was quick.

It should be fixed in 0.20.1: https://www.curseforge.com/minecraft/mc-mods/zetter/files/4381329 (could be 404 for a couple of minutes as file is processing). I'll take 0.20.0 down after CurseForge approves the new version.

Let me know if everything is good on the new version.
