### ISSUE TITLE
The "online manual" button links to zetter.gallery which is down

### ISSUE THREAD

**Issue by TheDeviantCrafter** [dantaeusb-mc/Zetter#31]
The artists table for example links to this site: https://zetter.gallery/wiki/zetter#painting

The Curseforge page links to a Github wiki. It's possible that this site is depricated.

**Comment by dantaeusb** [comment]
Hi! First, thank you very much for lots of suggestions and noticing that site is down. I wasn't actively watching the project last 2 weeks due to events you are probably aware of, so there were some issues keeping hosting up.

It should be okay now, and I'll look for some options to monitor site availability.

Looking forward to review other suggestions. I was focused on the Gallery website lately, which should allow players to upload and download paintings. If I'll be able to make a release soon, I'll be working on your suggestions.
