### ISSUE TITLE
Updates to new versions and backports

### ISSUE THREAD

**Issue by rostikmak** [dantaeusb-mc/Zetter#32]
Hello, sorry if I'm annoying, but can you tell at least approximately: when the mod will be released on 1.18.2.
I'm really looking forward to your mod on 1.18.2.
Translated by google translator.
He is wonderful.
Thanks a lot.
Have nice day! (this phrases written by me =) ).

**Comment by dantaeusb** [comment]
Hi! Unfortunately right now I can't estimate when I'll be able to continue my work as usual. I really want to continue my work as soon as possible, as I have a HUGE update coming on, so be sure that I'm working on it when I can, just off-schedule.

Thank you for your interest, and have a nice day too! 

P.S. I'm not sure if that's proper to say or you want to hear that, but basically mod is not updated because had to flee my country due to Russo-Ukrainian war (I'm Russian who does not support the war), and no not yet have a reliable place to stay and work normally. As soon as things will go better, I'll try my best to update and release new features.

**Comment by dantaeusb** [comment]
Also updated title so other people will be able to see that. I'll let yoy know as soon as I will release new version.

**Comment by rostikmak** [comment]
Спасибо за ответ, удачи вам во всём и мирного неба нам всем над головой, надеюсь это всё закончится скоро и придёт к чему-то хорошему.
А ещё вы меня очень заинтриговали тем что будет большое обновление: теперь будем ждать с ещё большим нетерпением(у меня сестра любит рисовать и в жизни и в майне, столько картин нарисовала с помощью вашего супермегахорошего мода)
А и я беларус и знаю русский=). Удачи ещё раз и ты крутой!

**Comment by dantaeusb** [comment]
Спасибо огромное!
Картины можно будет продавать деревенскому жителю -- продавцу картин, это позволит другим игрокам покупать ваши картины, такой инстаграм для картин в Minecraft :) Так что мод будет полезен не только тем, кто любит рисовать, но и тем, кто хочет расширить количество картин в Minecraft до бесконечности.
Всё уже почти готово, но никак не запущу, плюс для старых версий нужно патчи подготовить.
