### ISSUE TITLE
Paintings randomly disappear when broken.

### ISSUE THREAD

**Issue by Rimevel** [dantaeusb-mc/Zetter#34]
More than once paintings have vanished when I try to take them down by left-clicking :(
Lost so much good art.

Running latest version of the mod for 1.18.2

**Comment by Rimevel** [comment]
It seem to mainly be an issue with older paintings? Maybe an issue when saving and loading.

**Comment by dantaeusb** [comment]
Sounds terrible! That shouldn't have happened. It's usually possible to restore paintings, as painting data is stored outside the items and entities. If you don't mind, can you send me your world files to dantaeusb@live.com? I'll try to reproduce the issue and restore paintings.

I'll also need to know more info, i.e. which version you were updating from. 

If you don't wish to send world files for any reason, I understand that. I'll try to reproduce with the world files from older versions if I'll be able to find them.

**Comment by Rimevel** [comment]
I managed to reproduce the bug!

1. Put a painting inside a dark oak frame with a nameplate.
2. Hang it on a wall.
3. Take it down and take the painting out of the frame.
4. Put the painting in a dark oak frame WITHOUT a nameplate.
5. Gang it on a wall.
6. Try to take it down, but it disappears instead.

**Comment by dantaeusb** [comment]
Unfortunately, I cannot reproduce the issue following those steps. Trying to fall back to 1.16.5 to see if there are any issues with older paintings.

By the way, do you have other mods in your modpack? Not sure if that could be related.

Also, theoretically this is the easiest way to restore your paintings is:
1. Create a new painting of the same size as missing, no need to place it on a wall;
2. Save the world;
3. Locate Minecraft folder;
4. Open saves/{your world name}/data;
5. Find missing painting by checking `zetter_painting_N.dat` files [using NBTexplorer](https://minecraft.fandom.com/wiki/Programs_and_editors/NBTExplorer), let's say `zetter_painting_5.dat` is missing one;
6. Remove the latest painting (i.e. `zetter_painting_20.dat`) and copy `zetter_painting_5.dat` to `zetter_painting_20.dat`;
7. That way you'll replace the newly created painting with the missing painting -- next time you log in you should have your painting back.

**Comment by Rimevel** [comment]
Ty for the guide, will be good to know in the future :)
As for other mods I have a lot yes, so there may very well be a conflict 🤔 
I will report back if I find out anything new.

**Comment by dantaeusb** [comment]
Okay, the behavior is confirmed and unfortunately does not have a reasonable fix. It is happening because 1.18.2 datafixers wipes all data related to ALL mod entities and structures, basically everything non-vanilla is wiped. It is unreasonable to try to solve this issue in the scope of mod. I'll be watching for Forge and Minecraft updates and hope for some workaround to appear, as I'm not very experienced modder to contribute to the solution of this issue.

Looking out for this https://github.com/MinecraftForge/MinecraftForge/pull/8501 particularly, as it seems to be valid approach for solution, also maybe Forge team will manage to bypass all non-vanilla entries in world data, so I will not have to change anything.

I'm thinking to add a disclaimer for the mod's page and fallback to 1.16.5 as a primary version for development until there's some fix.

**Comment by dantaeusb** [comment]
On the other hand, I’m not sure the issue you describing is the same issue I faced with world update from 1.16.3. If you can, please provide the mod list.

**Comment by dantaeusb** [comment]
Cannot reproduce, going to update 1.16.3 as well to keep it consistent with 1.18.2, so I believe it should not be a problem anyways.
