### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by karltroid51** [dantaeusb-mc/Zetter#6]
Hello! I am using this mod on a dedicated server with my friends, and when I try to name my paintings, the server crashes. Attached is the most recent crash log. Thank you for any help in advance!

[crash-2021-06-29_17.14.38-server.txt](https://github.com/dantaeusb-mc/Zetter/files/6735215/crash-2021-06-29_17.14.38-server.txt)

**Comment by dantaeusb** [comment]
Hi!

Thank you for reporting, unfortunately I haven't had a time to test it on dedicated server properly and mod got a lot of attention suddenly while I was quickly building new updates and breaking some things :)

I've fixed that in Zetter-0.9.6-1.16.3-rc, but because CurseForge manually reviewing new updates it might be available to download only in a couple of hours there.

I've uploaded new version directly here: https://github.com/dantaeusb-mc/Zetter/releases/tag/0.9.6, hope it will work fine. 
There still might be some imperfections and issues around, but in general should be ok and painting data should never be lost even in those pre-releases.

**Comment by dantaeusb** [comment]
Also, please let me know here if it works fine. 

I've quickly tested it locally, but it still doesn't guarantee it will work for your environment, so I'm keeping this issue opened.

**Comment by karltroid51** [comment]
Thank you for the fix! It works perfectly now :)

**Comment by dantaeusb** [comment]
Good to hear! If you experience any other problems-- please don't hesitate to open up another issue. This mod is quite young, so I really need valuable feedback from real-world users.
