### ISSUE TITLE
Ticking Entity with Carry On

### ISSUE THREAD

**Issue by karltroid51** [dantaeusb-mc/Zetter#7]
Hi! It's me again! I seem to have a knack for prodding things in the wrong way ;w;

I proudly displayed my finished painting on a painting frame, and I wanted to take it down for relocation. I ended up however carrying it thanks to the Carry On mod. (https://www.curseforge.com/minecraft/mc-mods/carry-on)

Picking it up gives me an invisible entity with an untranslated string for Zetter's painting entity (which is also visible when using mods like WAILA/HWYLA, which might be something you want to take a look at) and I can't set it down via normal means, and on the off chance that I somehow put it down, it crashes the server. It took me a few crashes to figure out how to remove the anomalous painting from my inventory and go about with my day.

Attached are the several crash logs from my repeated attempts to remove the painting from my inventory and from Carry On's carrying system. Thank you for any help in advance!

[crash-2021-06-29_21.48.58-server.txt](https://github.com/dantaeusb-mc/Zetter/files/6736771/crash-2021-06-29_21.48.58-server.txt)
[crash-2021-06-29_21.51.51-server.txt](https://github.com/dantaeusb-mc/Zetter/files/6736772/crash-2021-06-29_21.51.51-server.txt)
[crash-2021-06-29_21.56.34-server.txt](https://github.com/dantaeusb-mc/Zetter/files/6736773/crash-2021-06-29_21.56.34-server.txt)

**Comment by dantaeusb** [comment]
Hi!

Yes, looks like there are problems with CarryOn. I think I know how to fix that, so that probably will be fixed soon too.

For the meantime, I can advise you to do the following:
1) Stay a little away from the easel to take the canvas without grabbing the whole easel;
2) In order to move the frame, you can do that as simple as you do with Vanilla paintings — just break it and place somewhere else;
3) If you want to restore your painting, you may create a new, empty painting, and replace its data with the old one. All paintings are permanently saved (even if removed as items or entities) in `saves/WorldName/`data/zetter_painting_x.dat`. If you copy data from an old, removed painting, to the new one, you'll be able to restore it. You may use the program called NBTExplorer to do that.

**Comment by dantaeusb** [comment]
New version with fix for CarryOn already available on CurseForge, you can upgrade. I'm thinking that carrying a hanging entity around is not a good idea anyway (I don't think we can say CarryOn that we can only put that entity on walls), therefore I've just forbidden carriage of easel and paintings + added a fallback name for entity name.

Thanks for the report, as always it's much appreciated.

I'll open up another issue related to the fact that an entity with missing data causing crash, but I don't think it's much of importance right now, so I'll take care of that later.
